# Wrangler Configuration File
# For deploying Workers using Cloudflare Wrangler CLI

name = "lensify-calculator"
main = "worker.js"
compatibility_date = "2023-05-18"

# Routes Configuration
[triggers]
routes = [
  { pattern = "lensify-calculator.yagami1997.workers.dev/*", zone_name = "workers.dev" }
]

# SSL Configuration
[ssl]
certificate_mode = "managed_by_cloudflare"

# Build Configuration
[build]
upload.exclude = [
  "*.md",
  "LICENSE",
  ".git",
  ".gitignore",
  ".DS_Store",
  "Thumbs.db"
]

# Cloudflare Pages Configuration
# Note: For Pages, use pages_build_output_dir instead of bucket
pages_build_output_dir = "lensify/public"

# Environment Variables Example
# [vars]
# API_KEY = "your-api-key-here"

# To install Wrangler CLI:
# npm install -g wrangler

# To deploy Worker:
# wrangler deploy 